server:
  port: 8081
spring:
  application:
    name: spam
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/spam
    username: ahsan
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true